CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(60) NOT NULL,
    email VARCHAR(50) NOT NULL,
    posts INT DEFAULT 0,
    comments INT DEFAULT 0,
    last_login DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    link VARCHAR(150),
    text VARCHAR(2000),
    created_dtm DATETIME DEFAULT CURRENT_TIMESTAMP
)

